### PR TITLE
add redis to docker-compose

### PR DESCRIPTION
**Pull request by wsmoyer**
i added redis to the docker-compose file conditionally

### CODE REVIEW

**Review by ahackit — COMMENTED** [review]
I think on these we decided we wanted separate docker-compose files, ya? So at runtime you combine compose files at will to decide what pieces of the stack we stand up.

**Comment by wsmoyer** [comment]
> I think on these we decided we wanted separate docker-compose files, ya? So at runtime you combine compose files at will to decide what pieces of the stack we stand up.

since this is just the template, i found out when you actually run this repo against the project you are going to create, the docker-compose file gets cleaned up anyway and only puts in there what you asked for.

**Comment by wsmoyer** [comment]
> > I think on these we decided we wanted separate docker-compose files, ya? So at runtime you combine compose files at will to decide what pieces of the stack we stand up.
> 
> since this is just the template, i found out when you actually run this repo against the project you are going to create, the docker-compose file gets cleaned up anyway and only puts in there what you asked for.

this is the command you run. cookiecutter gh:loftylabs/cookiecutter-django-vue

**Review by ahackit — APPROVED** [review]
🍰  from me. Might wait for @aFraley  @TyrelDenison's thoughts that this is the direction we were looking to have.

**Review by TyrelDenison — APPROVED** [review]
🍰

**Comment by TyrelDenison** [comment]
> 🍰 from me. Might wait for @aFraley @TyrelDenison's thoughts that this is the direction we were looking to have.

Good with that.

**Pull request merged**
